/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'das',
    path: '/das',
    component: 'layout.base',
    meta: {
      title: 'das',
      i18nKey: 'route.das',
      icon: 'mdi:database-search',
      order: 2
    },
    children: [
      {
        name: 'das_modules',
        path: '/das/modules',
        meta: {
          title: 'das_modules',
          i18nKey: 'route.das_modules'
        },
        children: [
          {
            name: 'das_modules_edit',
            path: '/das/modules/edit',
            component: 'view.das_modules_edit',
            meta: {
              title: 'das_modules_edit',
              i18nKey: 'route.das_modules_edit'
            }
          },
          {
            name: 'das_modules_favorite',
            path: '/das/modules/favorite',
            component: 'view.das_modules_favorite',
            meta: {
              title: 'das_modules_favorite',
              i18nKey: 'route.das_modules_favorite'
            }
          },
          {
            name: 'das_modules_history',
            path: '/das/modules/history',
            component: 'view.das_modules_history',
            meta: {
              title: 'das_modules_history',
              i18nKey: 'route.das_modules_history'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
